apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8-resource-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8-resources
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8-resources-roles
subjects:
  - kind: ServiceAccount
    name: k8-resource-service-account
roleRef:
  kind: ClusterRole
  name: k8-resources
  apiGroup: rbac.authorization.k8s.io