apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-resources-app
  labels:
    app: k8-resources-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-resources-app
  template:
    metadata:
      labels:
        app: k8-resources-app
    spec:
      serviceAccountName: k8-resource-service-account
      containers:
        - name: k8-resources-app
          image: dash04/k8resources:v20
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-k8-resources-app-service
spec:
  selector:
    app: k8-resources-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31289
  type: NodePort
